BASE_CAMERA_RESET_COUNT=10
BASE_CAMERA_RESET_DELAY=15ms
PRE_RESET_WAIT=50ms
POST_BASE_WAIT=250ms
WALK_FORWARD_DURATION=1s300ms
FIRST_DIAGONAL_DURATION=1s500ms
TELEPORT_WAIT=1s
SECOND_DIAGONAL_DURATION=1s500ms
MENU_OPEN_WAIT=200ms
POST_BUY_WAIT=700ms
WALK_AWAY_LEFT_DURATION=600ms
