BASE_TELEPORT_BUTTON_X=
BASE_TELEPORT_BUTTON_Y=
PLACE_HOLD_POINT_X=
PLACE_HOLD_POINT_Y=
PACK_CLICK_POINT_X=
PACK_CLICK_POINT_Y=

MENU_BUTTON_X=
MENU_BUTTON_Y=
POTION_2_MIN_X=
POTION_2_MIN_Y=
POTION_2_MIN_USE_SINGLE_BUTTON_X=
POTION_2_MIN_USE_SINGLE_BUTTON_Y=
POTION_2_MIN_USE_10X_BUTTON_X=
POTION_2_MIN_USE_10X_BUTTON_Y=

POTION_6_MIN_X=
POTION_6_MIN_Y=
POTION_6_MIN_USE_SINGLE_BUTTON_X=
POTION_6_MIN_USE_SINGLE_BUTTON_Y=
POTION_6_MIN_USE_10X_BUTTON_X=
POTION_6_MIN_USE_10X_BUTTON_Y=

POTION_15_MIN_X=
POTION_15_MIN_Y=
POTION_15_MIN_USE_SINGLE_BUTTON_X=
POTION_15_MIN_USE_SINGLE_BUTTON_Y=
POTION_15_MIN_USE_10X_BUTTON_X=
POTION_15_MIN_USE_10X_BUTTON_Y=

USE_SINGLE_BUTTON_X=
USE_SINGLE_BUTTON_Y=
USE_10X_BUTTON_X=
USE_10X_BUTTON_Y=
CLOSE_BUTTON_X=
CLOSE_BUTTON_Y=

ITEM_POINT_X=
ITEM_POINT_Y=
USE_BUTTON_X=
USE_BUTTON_Y=
